# Configuration of the numbat service
numbat:
  # Configuration of the amber database
  amber:
    # Configuration of the S3 API of the amber database
    s3:
      # Host of the S3 API
      host: amber.amber.svc.cluster.local

      # Password to authenticate with the S3 API
      password: password

      # Port of the S3 API
      port: 10610

      # Whether to use secure connection with the S3 API
      secure: false

      # User to authenticate with the S3 API
      user: readwrite

  # Configuration of the beaver service
  beaver:
    # Configuration of the HTTP API of the beaver service
    http:
      # Host of the HTTP API
      host: beaver.beaver.svc.cluster.local

      # Path of the HTTP API
      path: ""

      # Port of the HTTP API
      port: 10500

      # Scheme of the HTTP API
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Port to listen on
    port: 10600

# Configuration of the service
service:
  # Port to listen on
  port: 10600
