# Configuration of the howlite database
howlite:
  # Identifier of the calendar
  calendar: calendar

  # Credentials for the database
  credentials:
    # Password of the main user
    password: password

    # Username of the main user
    user: user

  # Configuration of the server
  server:
    # Port to listen on
    port: 10520

# Configuration of the service
service:
  # Port to listen on
  port: 10520
