# Configuration of the beaver service
beaver:
  # Enable debug mode
  debug: true

  # Howlite configuration
  howlite:
    # Configuration of the CalDAV API of the howlite service
    caldav:
      # Calendar to use for the CalDAV API
      calendar: calendar

      # Host of the CalDAV API
      host: howlite.howlite.svc.cluster.local

      # Password to authenticate with the CalDAV API
      password: password

      # Path of the CalDAV API
      path: ""

      # Port of the CalDAV API
      port: 10520

      # Scheme of the CalDAV API
      scheme: http

      # User to authenticate with the CalDAV API
      user: user

  # Sapphire configuration
  sapphire:
    # Configuration of the SQL API of the sapphire database
    sql:
      # Host of the SQL API
      host: sapphire.sapphire.svc.cluster.local

      # Password to authenticate with the SQL API
      password: password

      # Port of the SQL API
      port: 10510

  # Configuration of the server
  server:
    # Port to listen on
    port: 10500

# Configuration of the service
service:
  # Port to listen on
  port: 10500
