# Configuration of the amber database
amber:
  # Credentials for the database
  credentials:
    # Credentials for the admin user
    admin:
      # Password of the admin user
      password: password

      # Username of the admin user
      user: admin

    # Credentials for the readonly user
    readonly:
      # Password of the readonly user
      password: password

      # Username of the readonly user
      user: readonly

    # Credentials for the readwrite user
    readwrite:
      # Password of the readwrite user
      password: password

      # Username of the readwrite user
      user: readwrite

  # Configuration of the server
  server:
    # Ports to listen on
    ports:
      # Port to listen on for S3 connections
      s3: 10610

      # Port to listen on for web console traffic
      web: 10611

  # URLs configuration
  urls:
    # Public URL of the web interface
    web: http://localhost:10611

# Configuration of the service
service:
  # Ports to listen on
  ports:
    # Port to listen on for S3 connections
    s3: 10610

    # Port to listen on for web console traffic
    web: 10611
