# Configuration of the quokka service
quokka:
  # Credentials configuration
  credentials:
    # Credentials of the admin user
    admin:
      # Password of the admin user
      password: password

      # Username of the admin user
      user: admin

    # Credentials of the source user
    source:
      # Password of the source user
      password: password

      # Username of the source user
      user: source

  # Configuration of the server
  server:
    # Port to listen on
    port: 10000

# Configuration of the service
service:
  # Port to listen on
  port: 10000
