# Configuration of the graphite database
graphite:
  # Credentials for the database
  credentials:
    # Credentials for the main user
    user:
      # Password of the main user
      password: password

  # Configuration of the server
  server:
    # Port to listen on
    port: 10220

# Configuration of the service
service:
  # Port to listen on
  port: 10220
